-- insert into talenti values ('0_talenti','ALPHONSO MANGO SORBETTO','Our simple and delicious Alphonso Mango Sorbetto is made with the finest ripe mangoes of Maharashtra, pure sugar, and fresh lemon. It‚Äôs the perfect dairy-free and vegan treat that everyone can enjoy.', '4.7','139','MANGOS, WATER, SUGAR, DEXTROSE, LEMON JUICE, CAROB BEAN GUM');
-- insert into talenti values ('1_talenti','BANANA CARAMEL CRUNCH','This flavor was inspired by a classic southern dessert: banana pudding. We started with two smooth and creamy layers of banana pudding gelato and included a layer of our signature Dulce de Leche. To top it off, we mixed in baked pie crust pieces for a unique Talenti twist.', '4.2','25','MILK, BANANAS, SUGAR‚Ä†, WHEAT FLOUR, CREAM, NONFAT MILK, EGG YOLKS, WATER, EGG WHITES, COCONUT OIL, CORN SYRUP‚Ä†, LEMON JUICE, WHOLE EGGS, CAROB BEAN GUM, BAKING SODA, VANILLA EXTRACT, NATURAL FLAVOR, SALT');
-- insert into talenti values ('2_talenti','BELGIAN CHOCOLATE GELATO','Our Belgian Chocolate gelato is made with melted, imported Belgian chocolate blended until smooth with fresh milk, cream, eggs and a hint of vanilla. When it comes to chocolate gelato, there‚Äôs good, there‚Äôs better, and there‚Äôs Belgian.', '4.8','27','MILK, SUGAR, CREAM, EGG AND EGG YOLK, DEXTROSE, CHOCOLATE, COCOA (PROCESSED WITH ALKALI), COCOA BUTTER, CHOCOLATE, CAROB GUM, SOY LECITHIN, NATURAL FLAVOR');
-- insert into talenti values ('3_talenti','BLACK RASPBERRY CHOCOLATE CHIP GELATO','Tart and sweet, our Black Raspberry Chocolate Chip gelato combines black raspberries (from a lovely Oregon father/daughter-run raspberry farm, to boot) with rich chocolatey chips, all folded into a creamy gelato.', '4','105','MILK, SUGAR, CREAM, BLACK RASPBERRIES, DEXTROSE, CHOCOLATE (PROCESSED WITH ALKALI), COCONUT OIL, CAROB GUM, SOYBEAN OIL, VANILLA EXTRACT, SOY LECITHIN NATURAL FLAVOR');
-- insert into talenti values ('4_talenti','BLACK RASPBERRY VANILLA PARFAIT','This Layer was inspired by one of our favorite desserts ‚Äì parfaits. It‚Äôs well-balanced and has a warm and satisfying taste that we are obsessed with. We start with Black Raspberry gelato which is crafted with black raspberry puree that comes from a farm in the Pacific Northwest. Next, we add oat crisps (which are similar to a crunchy oatmeal cookie) and a third layer of Blueberry sauce which is made from all-American blueberries. Finally we add a fourth layer of vanilla gelato and a fifth layer of oat crisps. We think this Black Raspberry Vanilla Parfait is the perfect dessert!', '4.5','65','MILK, SUGAR, CREAM, BLACK RASPBERRY PUREE, ROLLED OATS, COCONUT OIL, WHEAT FLOUR, WATER, TAPIOCA SYRUP, BROWN SUGAR, BLUEBERRIES, DEXTROSE, NATURAL FLAVOR, SUNFLOWER LECITHIN, CAROB BEAN GUM, GUAR GUM, VANILLA EXTRACT, PECTIN, RED CABBAGE JUICE CONCENTRATE (FOR COLOR), SALT');
-- insert into talenti values ('5_talenti','CARAMEL APPLE PIE GELATO','We start by steeping real cinnamon sticks in fresh milk and cream to make our delectable cinnamon gelato, then blend in bits of flaky piecrust, apple pieces, and a caramel swirl to create this one-of-a-kind Caramel Apple Pie gelato. Our methods might be Italian, but this recipe clearly leans American. This is special batch gelato, meaning it‚Äôs only available for a few months when it‚Äôs in season!', '4.8','115','MILK, SUGAR, CREAM, DEXTROSE, SKIM MILK, WHEAT FLOUR, CINNAMON, DRIED APPLES, CORN SYRUP, VANILLA EXTRACT, CAROB GUM, COCONUT OIL, BAKING SODA, EGGS, SALT');
-- insert into talenti values ('6_talenti','CARAMEL COOKIE CRUNCH GELATO','This is one of our best-selling flavors that people can‚Äôt get enough of (and we don‚Äôt blame them)! In our Caramel Cookie Crunch gelato recipe, we blend chocolate cookies into our delicious sweet cream gelato, then add a swirl of our one-of-a-kind dulce de leche. This caramelly combo results in one of our finest flavors to-date that will keep you coming back for more.', '4.2','334','MILK, SUGAR, CREAM, SKIM MILK, COCONUT, PALM AND SOYBEAN OILS, DEXTROSE, COCOA (PROCESSED WITH ALKALI), ENRICHED FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), CORN SYRUP, SUNFLOWER LECITHIN, CAROB BEAN GUM, VANILLA EXTRACT, GUAR GUM, BAKING SODA, DRIED CANE SYRUP, COCOA, SOY LECITHIN, NATURAL FLAVOR, CORN STARCH, SALT');
-- insert into talenti values ('7_talenti','CARIBBEAN COCONUT GELATO','Fresh milk, cream, sugar and vanilla come together with tender coconut sourced from the Philippines‚Äîwhich is nowhere near the Caribbean. Just go with us on this one because geographical discrepancies taste amazing.', '4.5','112','MILK, SUGAR, CREAM, COCONUT CONCENTRATE, COCONUT, DEXTROSE, CAROB GUM, VANILLA EXTRACT, SALT');
-- insert into talenti values ('8_talenti','CHOCOLATE CHERRY CHEESECAKE','Cherry cheesecake is a classic dessert and we think our Chocolate Cherry Cheesecake Layer is a soon-to-be classic, as well. We started with a cheesecake gelato made with real cream cheese to taste exactly like cheesecake. In the second indulgent layer we added chocolate flakes to create a decadent texture. We followed this with a third layer of black cherry sauce made with U.S. grown black cherries. Next, we included another layer of cheesecake gelato. Finally, to replicate classic graham cracker crust, we crafted a fifth layer of graham cookie pieces.', '4.3','77','MILK, SUGAR, CREAM CHEESE (CREAM, MILK, CHEESE CULTURE, SALT, GUAR GUM, CAROB BEAN GUM, XANTHAN GUM), CREAM, CHOCOLATE, EGG YOLKS AND EGG WHITES, WHEAT FLOUR, WATER, DEXTROSE, CHERRY PUREE, CHERRY JUICE CONCENTRATE, COCONUT OIL, MILK FAT, COCOA BUTTER, WHEAT BRAN, LEMON JUICE CONCENTRATE, CHOCOLATE PROCESSED WITH ALKALI, NATURAL FLAVOR, HONEY, VANILLA EXTRACT, CAROB BEAN GUM, SOY LECITHIN, BAKING SODA, SALT, WHEAT GERM');
-- insert into talenti values ('9_talenti','CHOCOLATE CHIP COOKIE DOUGH GELATO','We begin with our vanilla gelato, add chocolate chip cookie dough pieces, then finish with bonus swirls of fudge, resulting in this gelato that‚Äôs a nostalgic blend of child and adulthood.', '2.8','104','MILK, SUGAR, CREAM, WHEAT FLOUR, DEXTROSE, SKIM MILK, CHOCOLATE LIQUOR, VANILLA EXTRACT, EGGS, COCOA (PROCESSED WITH ALKALI), MOLASSES, SOYBEAN OIL, CAROB BEAN GUM, RICE FLOUR, NATURAL FLAVOR, SALT, COCOA BUTTER, LEMON PEEL, SOY LECITHIN');
-- insert into talenti values ('10_talenti','CHOCOLATE PEANUT BUTTER CUP GELATO','Milk chocolate gelato shares the stage with peanut butter and mini peanut butter cups to create our chocolate peanut butter cup gelato. Best-tasting party ever? We‚Äôd say ‚Äúyes,‚Äù but our mouths are full.', '4.4','77','MILK, SUGAR, PEANUTS, CREAM, EGG AND EGG YOLK, DEXTROSE, COCONUT OIL, CHOCOLATE, COCOA (PROCESSED WITH ALKALI), COCOA BUTTER, SKIM MILK, SALT, CAROB BEAN GUM, SOY LECITHIN, NATURAL FLAVOR, COCOA, VANILLA EXTRACT');
-- insert into talenti values ('11_talenti','COCONUT ALMOND CHOCOLATE GELATO','This flavor is like if Caribbean Coconut Talenti took its best friends on vacation. Coconut shreds, semi-sweet chocolatey flakes, and salted roasted almonds make quite a party.', '4.8','82','MILK, SUGAR, CREAM, CHOCOLATE (PROCESSED WITH ALKALI), ALMONDS, COCONUT CONCENTRATE, COCONUT, DEXTROSE, COCONUT AND SOYBEAN AND SUNFLOWER OILS, SALT, CAROB BEAN GUM, SOY LECITHIN, VANILLA EXTRACT, NATURAL FLAVOR');
-- insert into talenti values ('12_talenti','COCONUT CHOCOLATE COOKIE','', '4.3','29','WATER, SUGAR, DESICCATED COCONUT, COCONUT OIL, WHEAT FLOUR, DEXTROSE, COCOA PROCESSED WITH ALKALI, ROLLED OATS, CHOCOLATE LIQUOR, BROWN SUGAR, CANOLA OIL, CAROB BEAN GUM, NATURAL FLAVOR, SEA SALT, SUNFLOWER LECITHIN, PECTIN, GUAR GUM, BAKING SODA, SALT, SOY LECITHIN');
-- insert into talenti values ('13_talenti','COFFEE CHOCOLATE CHIP GELATO','Coffee sourced from Brazil and Colombia, slow cooked into fresh milk and cream, with semisweet chocolatey chips to give it a Clearly Talenti taste. Be careful. Our Coffee Chocolate Chip gelato could turn you into a coffee gelato snob.', '4.5','108','MILK, SUGAR, EGG YOLK AND EGG, CREAM, DEXTROSE, CHOCOLATE (PROCESSED WITH ALKALI), COFFEE, COCONUT OIL, CAROB GUM, SOYBEAN OIL, NATURAL FLAVOR, SOY LECITHIN');
-- insert into talenti values ('14_talenti','COFFEE COOKIE CRUMBLE','Inspired by an affogato, Coffee Cookie Crumble, is a coffee lover‚Äôs dream. We began with cold brew gelato made with fair trade Brazilian and Colombian coffee beans and sprinkled in dark chocolate chunks. From there, we added vanilla gelato, a chocolate coffee sauce and finally traditional Italian Amaretti Cookies for a unique Talenti twist.', '4.4','26','MILK, SUGAR‚Ä†, CREAM, CHOCOLATE, EGG YOLKS, WATER, WHEAT FLOUR, CORN SYRUP‚Ä†, SKIM MILK, DEXTROSE‚Ä†, COCOA (PROCESSED WITH ALKALI), PALM OIL, NATURAL FLAVOR, MILK FAT, COFFEE, COCOA BUTTER, VANILLA EXTRACT, EGG WHITES, SOY LECITHIN, CAROB BEAN GUM, CHOCOLATE (PROCESSED WITH ALKALI), SUNFLOWER LECITHIN, PECTIN, LEMON JUICE CONCENTRATE, MOLASSES‚Ä†, BAKING SODA, SALT, GUAR GUM, LEMON PEEL');
-- insert into talenti values ('15_talenti','COLD BREW COFFEE SORBETTO','Our Cold Brew Coffee Sorbetto is created by perfectly blending fair-trade Brazilian and Colombian cold brew coffee with everything but the milk. If this sorbetto was a coffee, we‚Äôd call it a South Americano.', '4.5','131','WATER, SUGAR, EGG YOLKS AND EGG WHITES, COCONUT OIL, ALMONDS, COFFEE EXTRACT CONCENTRATE, DEXTROSE, CAROB BEAN GUM,VANILLA EXTRACT');
-- insert into talenti values ('16_talenti','DARK CHOCOLATE CHERRY','This Layer was inspired by a cherry cordial and features the perfect pairing of dark chocolate and black cherry. We started with our Double Dark Gelato which features sophisticated hints of vermouth. Followed by chocolate flakes, a black cherry sauce, more Double Dark Gelato and a fifth layer of fudge truffles, this refined flavor is sure to please a crowd.', '4.2','48','MILK, SUGAR, CREAM, EGG YOLKS AND EGG WHITES, CHOCOLATE, COCOA PROCESSED WITH ALKALI, COCONUT OIL, DEXTROSE, WATER, CHERRY PUREE, CANOLA OIL, VERMOUTH, CHERRY JUICE CONCENTRATE, MILK FAT, COCOA BUTTER, WHEY, LEMON JUICE CONCENTRATE, VANILLA EXTRACT, CHOCOLATE PROCESSED WITH ALKALI, CAROB BEAN GUM, COCOA, SOY LECITHIN, SALT, NATURAL FLAVOR');
-- insert into talenti values ('17_talenti','DARK CHOCOLATE SORBETTO','', '4.2','41','WATER, SUGAR, COCOA PROCESSED WITH ALKALI, DEXTROSE, COCONUT OIL, EGG YOLKS, EGG WHITES, CHOCOLATE LIQUOR, CAROB BEAN GUM, SEA SALT, NATURAL FLAVOR, PECTIN');
-- insert into talenti values ('18_talenti','DOUBLE DARK CHOCOLATE GELATO','Our Double Dark Chocolate gelato is blended with semisweet chocolate morsels and just a dash of vermouth. Is it possible to have a crush on a frozen dessert?', '4.3','50','MILK, SUGAR, CREAM, CHOCOLATE, EGG AND EGG YOLK, DEXTROSE, COCOA (PROCESSED WITH ALKALI), VERMOUTH, MILK FAT, COCOA BUTTER, CAROB GUM, CHOCOLATE (PROCESSED WITH ALKALI), SOY LECITHIN, VANILLA EXTRACT');
-- insert into talenti values ('19_talenti','FUDGE BROWNIE GELATO','Fudge Brownie gelato. Real, gooey, perfect brownies blended into our dark chocolate gelato. And we added a swirl of rich, dark fudge because we clearly wanted to go all in on this pint.', '4.7','34','MILK, SUGAR, CREAM, EGG AND EGG YOLK, CHOCOLATE, DEXTROSE, COCOA (PROCESSED WITH ALKALI), WHEAT FLOUR, PALM OIL, SKIM MILK, FRUCTOSE, BROWN SUGAR, CAROB GUM, COCOA, SOYBEAN OIL, SALT, NATURAL FLAVOR, SOY LECITHIN, CORN STARCH');
-- insert into talenti values ('20_talenti','HAZELNUT CHOCOLATE CHIP GELATO','Hazelnut combines with chocolatey chips and roasted hazelnut pieces to create this Clearly Talenti take on a classic. Hazelnut Chocolate Chip gelato: the clear choice if you‚Äôre sweet and nutty, and looking for your gelato doppelg√§nger.', '4.3','72','MILK, SUGAR, CREAM, HAZELNUTS, CHOCOLATE, DEXTROSE, MILK FAT, COCOA BUTTER, CAROB BEAN GUM, CHOCOLATE (PROCESSED WITH ALKALI), VANILLA EXTRACT, XANTHAN GUM, SOY LECITHIN');
-- insert into talenti values ('21_talenti','KEY LIME PIE GELATO','Real key lime puree provides a bold kick in this tangy, creamy Key Lime Pie gelato that combines with graham cracker swirls and pieces to create this pie-disguised-as-gelato that even a true Floridian could get behind. This is special batch gelato, meaning it‚Äôs only available for a few months when it‚Äôs in season!', '4.3','208','MILK, SUGAR, CREAM, DEXTROSE, WHEAT FLOUR, COTTONSEED OIL, WHOLE WHEAT GRAHAM FLOUR, COCONUT OIL, CANOLA OIL, CAROB GUM, VANILLA EXTRACT, PALM AND PALM KERNEL OIL, WHEAT BRAN, HONEY, NATURAL FLAVOR, SALT, MOLASSES, SOY LECITHIN, WHEAT GERM, CINNAMON');
-- insert into talenti values ('22_talenti','LEMON BERRY PIE','Inspired by a classic summer dessert, this Layer pairs sweet and tart lemon gelato, all-American blueberries with pie crust pieces and graham cracker cookies for double the pie! We steeped lemon zest in fresh cream, milk and sugar to create a perfect lemon gelato.', '4.2','31','MILK, SUGAR‚Ä†, CREAM, LEMON JUICE, WHEAT FLOUR, TAPIOCA SYRUP, WATER, COCONUT OIL, BLUEBERRIES, DEXTROSE‚Ä†, EGG YOLKS, PALM OIL, NATURAL FLAVOR, WHEAT BRAN, WHOLE EGG, CAROB BEAN GUM, GUAR GUM, SALT, BAKING SODA, LEMON PEEL, WHEAT GERM, SOY LECITHIN, PECTIN, RED CABBAGE JUICE (COLOR)');
-- insert into talenti values ('23_talenti','MADAGASCAN VANILLA BEAN GELATO','Fresh milk, sugar and cream are slow cooked and the finest vanilla beans are imported from Madagascar to create a rich, one-of-a-kind taste that‚Äôs anything but plain vanilla.', '3.9','198','MILK, SUGAR, CREAM, DEXTROSE, VANILLA EXTRACT, SUNFLOWER LECITHIN, CAROB BEAN GUM, GUAR GUM, NATURAL FLAVOR, LEMON PEEL');
-- insert into talenti values ('24_talenti','MEDITERRANEAN MINT GELATO','Our Mediterranean Mint gelato uses real mint leaves steeped for 45 full minutes to get the perfect mint taste that is only amplified by the bittersweet chocolate flecks found throughout this iconic pint.', '4.7','324','MILK, SUGAR, CREAM, CHOCOLATE, DEXTROSE, MILK FAT, COCOA BUTTER, SUNFLOWER LECITHIN, CAROB BEAN GUM, NATURAL FLAVOR, GUAR GUM, CHOCOLATE (PROCESSED WITH ALKALI), VANILLA EXTRACT, SOY LECITHIN, MINT LEAF EXTRACTIVES');
-- insert into talenti values ('25_talenti','MINT FUDGE COOKIE','In this Layer, our Mediterranean Mint Gelato is the star of the show. So, of course, we began with our Mediterranean Mint Gelato made with fresh mint leaves. We used chocolatey cookies for an extra crunch in our second layer and swirled in a third layer of fudge sauce. Next, we used even more Mediterranean Mint Gelato in the fourth layer and finished with chocolate cookie pieces in the final layer.', '4.7','52','MILK, SUGAR, CREAM, DEXTROSE, EGG YOLKS, CAROB GUM, VANILLA EXTRACT, NUTMEG, NATURAL FLAVOR');
-- insert into talenti values ('26_talenti','OLD WORLD EGGNOG GELATO','Made with fresh milk, sugar, cream, egg yolks, pure vanilla extract, and nutmeg, our Old World Eggnog gelato recipe proves that, eggnog is meant to be eaten with a spoon.', '4.6','33','MILK, SUGAR, CREAM, DEXTROSE, EGG YOLKS, CAROB GUM, VANILLA EXTRACT, NUTMEG, NATURAL FLAVOR');
-- insert into talenti values ('27_talenti','ORGANIC BROWN BUTTER CARAMEL','Here‚Äôs a nutty, brown buttery idea. Organic caramel gelato, plus brown butter caramel (with a nutty cooked note to it), plus brown butter caramel swirls, plus a spoon, plus you. Let us know if that works for you.', '4.5','20','ORGANIC SKIM MILK, ORGANIC CANE SUGAR, ORGANIC CREAM, ORGANIC MILK, ORGANIC BUTTER (CREAM, SALT). ORGANIC GLUCOSE SYRUP, ORGANIC EGG YOLKS, ORGANIC DEXTROSE, ORGANIC CARAMELIZED SUGAR (ORGANIC CANE SUGAR, WATER), BAKING SODA, PECTIN, ORGANIC CAROB BEAN GUM, ORGANIC VANILLA EXTRACT, SEA SALT');
-- insert into talenti values ('28_talenti','ORGANIC CHOCOLATE MOUSSE GELATO','Don‚Äôt mousse out on this. Our Organic Chocolate Mousse gelato features organic dark chocolate gelato, is swirled with fudge, and is whipped to perfection. It‚Äôs handcrafted flavor at it‚Äôs finest‚Äîand fluffiest.', '4.3','13','ORGANIC SKIM MILK, ORGANIC CANE SUGAR, ORGANIC CREAM, ORGANIC MILK, ORGANIC EGG WHITES AND EGG YOLKS, ORGANIC DEXTROSE, ORGANIC CHOCOLATE, ORGANIC COCOA PROCESSED WITH ALKALI, WATER, ORGANIC BUTTER (ORGANIC CREAM, SALT), ORGANIC CAROB BEAN GUM, ORGANIC BLACK COCOA PROCESSED WITH ALKALI');
-- insert into talenti values ('29_talenti','ORGANIC GINGER MATCHA GELATO','We love this flavor so matcha, we traveled all the way to Japan for it. Dive spoon first into the taste of green tea and organic ginger steeped in organic cream, blended with Japanese matcha. No passport needed.', '4.7','21','ORGANIC SKIM MILK, ORGANIC CANE SUGAR, ORGANIC CREAM, ORGANIC MILK, ORGANIC EGG WHITES AND EGG YOLKS, ORGANIC DEXTROSE, ORGANIC CHOCOLATE, ORGANIC COCOA PROCESSED WITH ALKALI, WATER, ORGANIC BUTTER (ORGANIC CREAM, SALT), ORGANIC CAROB BEAN GUM, ORGANIC BLACK COCOA PROCESSED WITH ALKALI');
-- insert into talenti values ('30_talenti','ORGANIC OAK-AGED VANILLA GELATO','Some things get better with age. Like our new Organic Oak-Aged Vanilla gelato, the mature, more sophisticated cousin of our classic Madagascan Vanilla. It‚Äôs an elevated gelato crafted with Organic bourbon Vanilla and hints of oak. It‚Äôs a taste you‚Äôll want to take your time with‚Äîbut might not be able to.', '4.8','19','INGREDIENTS: ORGANIC SKIM MILK, ORGANIC CREAM, ORGANIC CANE SUGAR, ORGANIC DEXTROSE, OAKWOOD EXTRACT, ORGANIC CAROB BEAN GUM, ORGANIC VANILLA EXTRACT');
-- insert into talenti values ('31_talenti','PACIFIC COAST PISTACHIO GELATO','Our rich, creamy, vegan Peanut Butter Fudge sorbetto features a decadent swirl of dairy-free fudge. Don‚Äôt be surprised if you find yourself asking ‚ÄúHow did my peanut butter find its way to the freezer? And how does it taste this good?‚Äù', '4.5','201','MILK, SUGAR, CREAM, PISTACHIOS, DEXTROSE, CAROB BEAN GUM, NATURAL FLAVOR, VANILLA EXTRACT');
-- insert into talenti values ('32_talenti','PEANUT BUTTER FUDGE SORBETTO','', '4.7','77','WATER, PEANUTS, SUGAR, DEXTROSE, SALT, COCOA PROCESSED WITH ALKALI, CORN SYRUP, COCONUT OIL, CHOCOLATE, CORN STARCH, SEA SALT, VANILLA EXTRACT, CAROB BEAN GUM, GUAR GUM, XANTHAN GUM');
-- insert into talenti values ('33_talenti','PEANUT BUTTER VANILLA FUDGE','Our Peanut Butter Vanilla Fudge layer started with a decadent peanut butter gelato that is made with real salted peanut butter, (ground peanuts and salt) followed by fair trade peanut butter cups. Next, we added a fudge sauce, a vanilla gelato and finished with peanut butter cookie pieces.', '4.6','38','MILK, SUGAR, CREAM, PEANUTS, COCONUT OIL, WHEAT FLOUR, SKIM MILK, WATER, COCOA PROCESSED WITH ALKALI, BUTTER (CREAM, SALT), CHOCOLATE, DEXTROSE, PEANUT OIL, BROWN SUGAR, EGGS, NATURAL FLAVOR, SALT, SUNFLOWER LECITHIN, VANILLA EXTRACT, CAROB BEAN GUM, COCOA, BAKING SODA, GUAR GUM, SOY LECITHIN');
-- insert into talenti values ('34_talenti','PEPPERMINT BARK GELATO','A white chocolate peppermint gelato and semisweet chocolatey flakes combine for our Peppermint Bark gelato that tastes like winter in a pint.', '4.4','71','MILK, SUGAR, CREAM, CHOCOLATE (PROCESSED WITH ALKALI), DEXTROSE, COCOA BUTTER, COCONUT AND SOYBEAN OIL, VANILLA EXTRACT, CAROB GUM, SOY LECITHIN, NATURAL FLAVOR');
-- insert into talenti values ('35_talenti','PUMPKIN PIE','Pumpkin Pie Layers is the ultimate holiday dessert in jar! We began with an indulgent layer of pumpkin gelato, followed by a layer of pie crust pieces. We then added a layer of rich brown sugar sauce (the same one we used in our original pumpkin pie flavor). And lastly, another layer of pumpkin gelato then more pie crust pieces!', '4.6','63','MILK, SUGAR‚Ä†, CREAM, WHEAT FLOUR, PUMPKIN, WATER, BUTTER, BROWN SUGAR‚Ä†, COCONUT OIL, DEXTROSE‚Ä†, TAPIOCA STARCH, EGG, SUNFLOWER LECITHIN, CINNAMON, NATURAL FLAVOR, CAROB BEAN GUM, SALT, CARROT POWDER (COLOR), NUTMEG, GUAR GUM, VANILLA EXTRACT');
-- insert into talenti values ('36_talenti','RASPBERRY CHEESECAKE GELATO','We blend real cream cheese with graham cracker crust pieces and a raspberry swirl to create our Raspberry Cheesecake gelato. It‚Äôs the perfect choice when you‚Äôre looking to order a la mode but don‚Äôt want the cake half of the equation.', '3.9','76','MILK, SUGAR, CREAM, CREAM CHEESE (MILK, CREAM, CHEESE CULTURE, SALT, CAROB GUM, GUAR GUM, XANTHAN GUM), CORN SYRUP, ENRICHED FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THAIMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), BALSAMIC VINEGAR (RED WINE VINEGAR, GRAPE MUST), EGG, WHOLE WHEAT GRAHAM FLOUR, RASPBERRY PUREE, VANILLA EXTRACT, CAROB GUM, MODIFIED CORN STARCH, PALM OIL, BROWN SUGAR, NATURAL FLAVOR, COLOR ADDED, CARRAGEENAN, HONEY, SALT, SOY LECITHIN');
-- insert into talenti values ('37_talenti','ROMAN RASPBERRY SORBETTO','Packed with raspberries, this non-dairy, vegan sorbetto is intensely flavorful. With hints of lemon, it‚Äôs the perfect balance of tang and sweetness.', '4.7','161','RASPBERRIES, WATER, SUGAR, DEXTROSE, LEMON JUICE, CAROB BEAN GUM');
-- insert into talenti values ('38_talenti','SALTED CARAMEL TRUFFLE','', '4.7','160','MILK, SUGAR, SKIM MILK, CREAM, WATER, COCONUT OIL, CORN SYRUP, WHOLE EGG AND EGG YOLK, COCOA PROCESSED WITH ALKALI, ENRICHED WHEAT FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), DEXTROSE, PALM OIL AND SOYBEAN OIL, BAKING SODA, VANILLA EXTRACT, CAROB BEAN GUM, SUNFLOWER LECITHIN, SEA SALT, SOY LECITHIN, NATURAL FLAVOR, DRIED CANE SYRUP, COCOA, BUTTER (CREAM, SALT), GUAR GUM, CORN STARCH, SALT');
-- insert into talenti values ('39_talenti','SEA SALT CARAMEL GELATO','', '4.1','146','MILK, SKIM MILK, SUGAR, CREAM, EGG YOLK AND WHOLE EGG, CORN SYRUP, COCONUT OIL, DEXTROSE, COCOA (PROCESSED WITH ALKALI), SEA SALT, CAROB BEAN GUM, VANILLA EXTRACT, SOY LECITHIN, NATURAL FLAVOR');
-- insert into talenti values ('40_talenti','SOUTHERN BUTTER PECAN GELATO','Roasted pecans coated in butter and a dulce de leche swirl give our Southern Butter Pecan gelato its premium taste. Best enjoyed on rocking chair, on a porch, with a ceiling fan.', '4.2','125','MILK, SUGAR, CREAM, PECANS, EGG YOLK AND EGG, DEXTROSE, SKIM MILK, MOLASSES, CORN SYRUP, CAROB BEAN GUM, COTTONSEED OIL, VANILLA EXTRACT, SALT, NATURAL FLAVOR, SEA SALT');
-- insert into talenti values ('41_talenti','STRAWBERRY HIBISCUS SORBETTO','Sweet strawberries and real hibiscus flowers are blended together for a perfectly sweet and tart dairy-free sorbetto. There is ¬º cup of real strawberries in each serving! For a pop of color, we finish with a beautiful hibiscus swirl to complete this delicious refreshing sorbetto.', '4.4','14','WATER, STRAWBERRIES, SUGAR, DEXTROSE, CORN SYRUP, LEMON JUICE, HIBISCUS POWDER, HIBISCUS FLOWER, CAROB BEAN GUM, LIME JUICE CONCENTRATE, PECTIN, VEGETABLE JUICE (FOR COLOR)');
-- insert into talenti values ('42_talenti','VANILLA BLUEBERRY CRUMBLE GELATO','Our Vanilla Blueberry Crumble gelato starts with our vanilla bean gelato and is combined with a real blueberry sauce and brown sugar covered oat crumbles. It‚Äôs like eating a delicious, crispy baked dessert a la mode, all at once.', '3.9','70','MILK, SUGAR, CREAM, TAPIOCA SYRUP, DEXTROSE, ROLLED OATS, COCONUT OIL, WHEAT FLOUR, BLUEBERRIES, VANILLA EXTRACT, BROWN SUGAR, NATURAL FLAVOR, CAROB BEAN GUM, VANILLA BEANS, PECTIN, GUAR GUM, COLOR ADDED, SALT, CITRIC ACID, LEMON PEEL');
-- insert into talenti values ('43_talenti','VANILLA CARAMEL SWIRL GELATO','Our Vanilla Caramel Swirl gelato is our simple vanilla bean gelato combined with our rich dulce de leche. It begs the question, ‚ÄúWhere have you been all my life?‚Äù', '3.6','38','MILK, SUGAR, CREAM, SKIM MILK, DEXTROSE, VANILLA EXTRACT, CORN SYRUP, CAROB GUM, NATURAL FLAVOR, LEMON PEEL, VANILLA BEANS');
-- insert into talenti values ('44_talenti','VANILLA FUDGE COOKIE','Vanilla Fudge Cookie features two of our iconic gelato flavors! We started with our Talenti Double Dark Gelato on top, then created a layer of chocolate cookie chunks, followed by a fudge sauce. Next, we mixed in our Madagascan Vanilla Bean Gelato and finally, a fifth layer of chocolatey waffle cones to add a savory and sweet crunch.', '4.3','114','MILK, SUGAR, SKIM MILK, CREAM, WATER, COCONUT OIL, CORN SYRUP, WHOLE EGG AND EGG YOLK, COCOA PROCESSED WITH ALKALI, ENRICHED WHEAT FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), DEXTROSE, PALM OIL AND SOYBEAN OIL, BAKING SODA, VANILLA EXTRACT, CAROB BEAN GUM, SUNFLOWER LECITHIN, SEA SALT, SOY LECITHIN, NATURAL FLAVOR, DRIED CANE SYRUP, COCOA, BUTTER (CREAM, SALT), GUAR GUM, CORN STARCH, SALT');

-- insert into talentiReviews values ('0_talenti','amys','6/22/18','5','Mango Madness','12','0', 'Y‚Äôall! I‚Äôm sick as a dog!!! For reals! Temp of over 101. Begged my mom to get me some talenti because it‚Äôs my new favorite again. Anyways I told her to get something non-dairy for my throat so it wouldn‚Äôt get all yucky. She brings me this flavor. O.M.G. THIS IS SO GOOD!!!!! Ok, I have a cold so everything tastes bland so this shouldn‚Äôt be all that great right? No. This tastes like the actual mango, but like better than the actual mango!!! Seriously! Every flavor I try is my new favorite!! I 100% recommend this and all the other flavors! Talenti is the best. Oh! And there‚Äôs always a treat at the end. You can reuse the container. These guys are the best!!');
-- insert into talentiReviews values ('0_talenti','Hesskr','10/29/17','5','Mangos Mashed Up','21','0', 'This is seriously like eating fresh mangoes smashed up and put into a container. Many other surveys on the market remind me to much of ice cream and have a creaminess to them. Some people enjoy this, however I prefer a sorbet to taste just like fresh fruit. The ingredients in this could not be more direct. Mangoes, sugar, water, dextrose And lemon juice. At first I did not think I would like the tartness from the lemon juice. However it gives just a bit of lemon flavor, Which almost accentuates the mangoes. This is by far our favorite!');
-- insert into talentiReviews values ('1_talenti','joelle','3/4/20','5','Going Bananas!','12','0', 'Im such a fan of all Talent flavors, but the Banana Caramel Crunch is one of my favorites!. The layers create the perfect combination of YUM!!!! The textures all come together to make this gelato such an indulgent treat!!! It reminds me of a frozen version of Banana Foster! So good!');
-- insert into talentiReviews values ('1_talenti','DesiCakes','5/14/20','4','Subtle banana flavor','5','0', 'Most Banana products have a artificial flavor, which isnt the best tasting. However this Gelato doesnt have that gross artificial taste. It was really good on its own but even more so with the caramel and shortbread. I honestly wish there was more caramel because it really doesnt have a lot and you can barely taste it, had to add my own. But overall if you like Banana, you will like this! I recommend giving it a shot.');
-- insert into talentiReviews values ('2_talenti','DoctorEsq','9/25/17','5','Creamy Richness','24','2', 'Im typically more of a dark chocolate devotee, but this Belgium Milk Chocolate gelato is so rich and creamy, it has become my absolute favorite (and I eat a 1/2 pint at a sitting easily!) Thank You, Talenti!!');
-- insert into talentiReviews values ('2_talenti','VILJ','9/25/17','5','Great Taste!','7','0', 'This was the first flavor of Talenti products that I tried and I have been buying Talentis gelato and sorbetto ever since. This Belgium Chocolate is great . Smooth and tasty.');
-- insert into talentiReviews values ('3_talenti','Alex','9/25/17','2','No chocolate chips?','12','0', '"Am I missing something? I dont know if I got a bad pint or something but there were no chocolate chips whatsoever in my gelato. Raspberry flavor was fine, nothing special. I usually love talenti, and my family and I have been customers for several years but Ive never tried this flavor. Overall disappointed. Not your best, talenti.');
-- insert into talentiReviews values ('3_talenti','Paulus','9/25/17','5','Wonderful texture! Fantastic flavor!','5','0', '"Just recently came upon your brand through your Raspberry Sorbetto. Now Im on to your gelati! Having spent many summers in Europe, particularly in Italy and Austria, I know what to expect when it comes to gelato. You guys have hit the nail on the head with this product! I plan to work my way through your flavors. Only one is missing, that I always get when Im over there, and that is hazelnut gelato...extremely popular in Europe. I also appreciate that Im getting my moneys worth when I buy your product. Your containers are a full pint (16 oz.), a good 2 to 3 oz. more than the other brands which cost the same! Keep up the good work!"');
-- insert into talentiReviews values ('4_talenti','Conthecat','5/5/20','3','Mix it in and just make it bigger','0','1', 'sucks');
-- insert into talentiReviews values ('4_talenti','Nikole','6/20/18','5','Its like Breakfast for Dessert!','12','0', 'Y‚Äôall! I‚Äôm sick as a dog!!! For reals! Temp of over 101. Begged my mom to get me some talenti because it‚Äôs my new favorite again. Anyways I told her to get something non-dairy for my throat so it wouldn‚Äôt get all yucky. She brings me this flavor. O.M.G. THIS IS SO GOOD!!!!! Ok, I have a cold so everything tastes bland so this shouldn‚Äôt be all that great right? No. This tastes like the actual mango, but like better than the actual mango!!! Seriously! Every flavor I try is my new favorite!! I 100% recommend this and all the other flavors! Talenti is the best. Oh! And there‚Äôs always a treat at the end. You can reuse the container. These guys are the best!!');
-- insert into talentiReviews values ('5_talenti','Tanjoru','6/22/21','5','Bland Gelato','12','0', 'i love it');
-- insert into talentiReviews values ('5_talenti','Nezoku','6/22/15','5','Delicious!','12','0', 'little salty and sweet but its good');

-- insert into bj values ('0_bj','Salted Caramel Core','Sweet Cream Ice Cream with Blonde Brownies & a Salted Caramel Core','Sometimes ‚Äúchip‚Äù happens and everything‚Äôs a mess, but we Nailed It! with this chip-filled limited batch. When smooth chocolate ice cream meets fudge chips & salty swirls, they pack a serious one-two crunch. The best part? There won‚Äôt be anything left to clean up.ltimate ice cream experience with our Cores. Whether your primal urges lead you to the center of salted caramel or directly to the blonde brownies, you‚Äôll be in total control of your own ice cream destiny.','3.7','208','CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, BROWN SUGAR, SUGAR, MILK, WHEAT FLOUR, EGG YOLKS, CORN SYRUP, EGGS, BUTTER (CREAM, SALT), BUTTEROIL, PECTIN, SEA SALT, SOYBEAN OIL, VANILLA EXTRACT, GUAR GUM, SOY LECITHIN, BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORN STARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT, CARRAGEENAN, LACTASE');
-- insert into bj values ('1_bj','Netflix & Chill','Peanut Butter Ice Cream with Sweet & Salty Pretzel Swirls & Fudge Brownies','As a Limited Batch that captured the rapture of the classic Sicilian dessert, our Cannoli captivated fans like no other Cannoli could. Now that it‚Äôs a full-time flavor, you and your Cannoli can re-capture the rapture all over again.ltimate ice cream experience with our Cores. Whether your primal urges lead you to the center of salted caramel or directly to the blonde brownies, you‚Äôll be in total control of your own ice cream destiny.','4','208','CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, BROWN SUGAR, SUGAR, MILK, WHEAT FLOUR, EGG YOLKS, CORN SYRUP, EGGS, BUTTER (CREAM, SALT), BUTTEROIL, PECTIN, SEA SALT, SOYBEAN OIL, VANILLA EXTRACT, GUAR GUM, SOY LECITHIN, BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORN STARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT, CARRAGEENAN, LACTASE');
-- insert into bj values ('2_bj','Chip Happens','A Cold Mess of Chocolate Ice Cream with Fudge Chips & Crunchy Potato Chip Swirls','It‚Äôs a gimme: there‚Äôs always room for s‚Äômore. And we‚Äôre pretty sure you‚Äôll want to make s‚Äômore room in your freezer for this ‚Äòshmallowy-rich, graham-good-‚Äòn-chocolatey concoction now that its full time flavor!.ltimate ice cream experience with our Cores. Whether your primal urges lead you to the center of salted caramel or directly to the blonde brownies, you‚Äôll be in total control of your own ice cream destiny.','4.7','208','CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, BROWN SUGAR, SUGAR, MILK, WHEAT FLOUR, EGG YOLKS, CORN SYRUP, EGGS, BUTTER (CREAM, SALT), BUTTEROIL, PECTIN, SEA SALT, SOYBEAN OIL, VANILLA EXTRACT, GUAR GUM, SOY LECITHIN, BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORN STARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT, CARRAGEENAN, LACTASE');
-- insert into bj values ('3_bj','Cannoli','Mascarpone Ice Cream with Fudge-Covered Pastry Shell Pieces & Mascarpone Swirls','If you were more than a little bit smitten with half baked¬Æ‚Äôs peanut buttery cousin when it was a Limited Batch, we expect you could be a whole lot smittener now that it‚Äôs a full-time flavor. Enjoy!ltimate ice cream experience with our Cores. Whether your primal urges lead you to the center of salted caramel or directly to the blonde brownies, you‚Äôll be in total control of your own ice cream destiny.','3.6','208','CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, BROWN SUGAR, SUGAR, MILK, WHEAT FLOUR, EGG YOLKS, CORN SYRUP, EGGS, BUTTER (CREAM, SALT), BUTTEROIL, PECTIN, SEA SALT, SOYBEAN OIL, VANILLA EXTRACT, GUAR GUM, SOY LECITHIN, BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORN STARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT, CARRAGEENAN, LACTASE');
-- insert into bj values ('4_bj','Gimme S‚Äômore!‚Ñ¢','Toasted Marshmallow Ice Cream with Chocolate Cookie Swirls, Graham Cracker Swirls & Fudge Flakes','From the sweet blackberry and crazy creamy mascarpone ice creams to the shortbread cookies and fudge-dunked almonds, you‚Äôll fall in love with this flavor faster than you can say ‚Äúmass-car-po-nay.‚Äùltimate ice cream experience with our Cores. Whether your primal urges lead you to the center of salted caramel or directly to the blonde brownies, you‚Äôll be in total control of your own ice cream destiny.','4.5','208','CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, BROWN SUGAR, SUGAR, MILK, WHEAT FLOUR, EGG YOLKS, CORN SYRUP, EGGS, BUTTER (CREAM, SALT), BUTTEROIL, PECTIN, SEA SALT, SOYBEAN OIL, VANILLA EXTRACT, GUAR GUM, SOY LECITHIN, BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORN STARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT, CARRAGEENAN, LACTASE');
-- insert into bj values ('5_bj','Peanut Butter Half Baked¬Æ','Chocolate & Peanut Butter Ice Creams Mixed with Gobs of Peanut Butter Cookie Dough & Fudge Brownies','From the sweet blackberry and crazy creamy mascarpone ice creams to the shortbread cookies and fudge-dunked almonds, you‚Äôll fall in love with this flavor faster than you can say ‚Äúmass-car-po-nay.‚Äùltimate ice cream experience with our Cores. Whether your primal urges lead you to the center of salted caramel or directly to the blonde brownies, you‚Äôll be in total control of your own ice cream destiny.','4.9','208','CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, BROWN SUGAR, SUGAR, MILK, WHEAT FLOUR, EGG YOLKS, CORN SYRUP, EGGS, BUTTER (CREAM, SALT), BUTTEROIL, PECTIN, SEA SALT, SOYBEAN OIL, VANILLA EXTRACT, GUAR GUM, SOY LECITHIN, BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORN STARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT, CARRAGEENAN, LACTASE');

.mode csv
.separator ","
.headers on
.import /Users/Duy/Desktop/CSE/CSE_111/ice-cream-ratings/data/talenti/products.csv talenti
.import /Users/Duy/Desktop/CSE/CSE_111/ice-cream-ratings/data/talenti/reviews.csv talentiReviews
.import /Users/Duy/Desktop/CSE/CSE_111/ice-cream-ratings/data/bj/products.csv bj
.import /Users/Duy/Desktop/CSE/CSE_111/ice-cream-ratings/data/bj/reviews.csv bjReviews
.import /Users/Duy/Desktop/CSE/CSE_111/ice-cream-ratings/data/hd/products.csv hd
.import /Users/Duy/Desktop/CSE/CSE_111/ice-cream-ratings/data/hd/reviews.csv hdReviews
.import /Users/Duy/Desktop/CSE/CSE_111/ice-cream-ratings/data/breyers/products.csv breyers
.import /Users/Duy/Desktop/CSE/CSE_111/ice-cream-ratings/data/breyers/reviews.csv breyersReviews
.import /Users/Duy/Desktop/CSE/CSE_111/ice-cream-ratings/data/combined/products.csv combinedProducts
.import /Users/Duy/Desktop/CSE/CSE_111/ice-cream-ratings/data/combined/reviews.csv combinedReviews



-- insert into breyers values
-- insert into breyersReviews values
-- insert into hd VALUES
-- insert into hdReviews values
-- insert into bj values
-- insert into bjReviews values
-- insert into combinedProducts values
-- insert into combinedReviews values

-- insert into productFlavor values ('','');
-- insert into flavor values ('','');
-- insert into productIngredient values ('','');
-- insert into ingredient values ('','');
-- insert into productFlavor values
-- insert into flavor values
-- insert into productIngredient values
-- insert into ingredient values